### ISSUE TITLE
This is a heinous assault on sense and sensibility.

### ISSUE THREAD

**Issue by cheeryfella** [braposo/graphql-css#8] opened 2018-11-15 02:52 UTC
Why, on God's green Earth, would you contaminate your data with concerns of the presentation layer?

**Comment by rajington** [comment] 2018-11-20 05:19
In your CSS:
- How do you do themes?
- How do you currently use variables?
- How do you parameterize them?
- Are you familiar with CSS-in-JS (especially glamorous) and see its advantages?
- Do you understand how they are compiled in a reusable way and optimized for the DOM?

**Comment by rajington** [comment] 2018-11-20 05:29
@braposo this topic keeps on coming up, maybe it's worth a README section

**Comment by braposo** [comment] 2018-11-21 13:10
Hi @cheeryfella, thanks for opening the issue! And a big thanks to @rajington for the detailed reply!

This is something that has come up in the past (https://github.com/braposo/graphql-css/issues/3) and it's perfectly normal to raise these type of questions. 

The truth is that everything has the meaning each one of us attaches to it. The same thing might be great for some and awful for others. Things, which includes this library, don't really have a pre-defined meaning so it's quite hard to answer to these questions in a meaningful way. 

I'm going to the address this in the upcoming v2, which will feature a much simpler API and improved README. I'm also closing this as a duplicate of https://github.com/braposo/graphql-css/issues/3

**Closed by braposo** 2018-11-21 13:10 UTC
