### ISSUE TITLE
Is this a joke?

### ISSUE THREAD

**Issue by Arrow7000** [braposo/graphql-css#3] opened 2018-03-20 19:35 UTC
Sorry I just have to ask... is this a joke? I can't work out if it is or isn't.

If it is: well done :clap:.

If not... please explain why you made this. I'm genuinely curious.

**Comment by braposo** [comment] 2018-03-20 22:24
Hi @Arrow7000, thanks for opening the issue! This is clearly a question that we've been having a lot lately, so it must be something lingering on people's mind. Thanks for stepping forward!

I'm going to link to a tweet I've recently posted that talks precisely about it and I think it will help you understand a bit better: https://twitter.com/braposo/status/976123902433906690

Like I said in that tweet, we can't control how people feel, there have been a lot of mixed reactions in the community, but the most important lesson is that people seem to agree that this is challenging our view of the world, and that's a positive thing right?

Why would GraphQL be used to generate CSS? That's what we hope to answer soon, so stay tuned! Some of our partners during the closed alpha release found very interesting use-cases that we plan on revealing to the public.

In the meantime I'm going to close this as a duplicate of #1 as it seems to be a problem with the information in the docs.

Thanks again!

**Closed** 2018-03-20 22:25 UTC
Labels: duplicate

**Comment by developer239** [comment] 2018-07-30 13:34
@Arrow7000 @braposo I also think that this is a joke but one the other hand, imagine your project without CSS. No CSS after all those years. That would be kind of cool. 🙂
